language: ruby
cache: bundler
env:
  - CONTROLREPO_env="$TRAVIS_BRANCH"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.7
  - 2.2.3
script: bundler exec rake controlrepo_spec
bundler_args: --without acceptance development
